asyncapi: 2.6.0
id: 'form-flow-valtimo-events:1'
info:
    title: Valtimo Form Flow
    description: sdfgqeriuhg
    version: '1.0.0'
    license:
        name: EUPL-1.2
        url: https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
    contact:
        name: API Support
        url: https://www.ritense.com/contact
        email: support@ritense.com
channels:
    valtimo-audit:
        publish:
            operationId: 'fweqr'
            message:
                $ref: '#/components/messages/formFlowStepCompleted'

components:
    messages:
        formFlowStepCompleted:
            #schemaFormat: 'application/cloudevents+json; version=0.2; charset=utf-8'
            messageId: formFlowStepCompleted
            payload:
                $ref: "#/components/schemas/formFlowStepCompleted"

    schemas:
        formFlowStepCompleted:
            type: object
            properties:
                id:
                    type: string
                    format: uuid
                instanceId:
                    type: string
                    format: uuid
                stepKey:
                    type: string
                order:
                    type: integer
                submissionData:
                    type: string

servers:
    production:
        url: 'https://api.example.com'
        protocol: https
        protocolVersion: '1.1'

defaultContentType: application/json