asyncapi: 2.6.0
id: 'form-flow-valtimo-events:1'
info:
    title: Valtimo Form Flow
    description: sdfgqeriuhg
    version: '1.0.0'
    license:
        name: Apache 2.0
        url: https://www.apache.org/licenses/LICENSE-2.0.html
    contact:
        name: API Support
        url: https://www.example.com/support
        email: support@example.com
channels:
    valtimo-audit:
        publish:
            operationId: 'fweqr'
            message:
                #schemaFormat: 'application/cloudevents+json; version=0.2; charset=utf-8'
                messageId: 'asdf'
                payload:
                    type: object
                    properties:
                        id:
                            type: string
                            format: uuid
                        instanceId:
                            type: string
                            format: uuid
                        stepKey:
                            type: string
                        order:
                            type: integer
                        submissionData:
                            type: string

servers:
    production:
        url: 'https://api.example.com'
        protocol: https
        protocolVersion: '1.1'

defaultContentType: application/json